config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # You might think that using resource only for index is strange.
  # This looks familiar and it's clear that what i'm doing to
  resources :greeter, only: %i[index] do
    collection { get 'about' }
  end

  resource :sessions, only: %i[new create destroy]
  resources :users, except: %i[index] do
    member { post :update_role }
  end
  resources :posts
  resources :roles, except: %i[index show] do
    collection { post :search }
  end
  resources :grants, except: %i[index show] do
    collection { post :search }
  end
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  resources :passwords, except: %i[index destroy show], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection { delete 'destroy_all' }
  end

  root to: 'greeter#index'
end

app/views/shared/_alerts.html.erb
<% flash.each do |type, msg| %>
  <% if type == "alert" %>
    <%= content_tag :div, msg,
      class: "alert alert-danger alert-dismissible fade show",
      role: "alert" %>
  <% elsif type == "notice" %>
    <%= content_tag :div, msg,
      class: "alert alert-success alert-dismissible fade show",
      role: "alert" %>
  <% end %>
<% end %>

app/views/shared/_control_panel.html.erb
<div id="manageUser" class="modal fade p-10" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 id="manageUserLabel" class="modal-title">Manage all of the Peasants!</h1>
        <button class="btn-close" type="button" data-bs-dismiss="modal"
        aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul id="roleTab" class="nav nav-tabs" role="tablist">
          <li class="nav-item" role="presentation">
            <button
                id="add-role-tab"
                class="nav-link active"
                data-bs-toggle="tab" data-bs-target="#addRoleTab"
                type="button" role="tab"
                aria-controls="addRoleTab" aria-selected="true">
                Add New Role</button>
          </li>
          <li clas="nav-item" role="presentation">
            <button
                id="search-role-tab"
                class="nav-link"
                data-bs-toggle="tab" data-bs-target="#searchRoleTab"
                type="button" role="tab"
                aria-controls="searchRoleTab" aria-selected="false">
                Edit Role</button>
          </li>
          <li clas="nav-item" role="presentation">
            <button
                id="new-grant-tab"
                class="nav-link"
                data-bs-toggle="tab" data-bs-target="#newGrantTab"
                type="button" role="tab"
                aria-controls="newGrantTab" aria-selected="false">
                Add New Grant</button>
          </li>
          <li clas="nav-item" role="presentation">
            <button
                id="search-grant-tab"
                class="nav-link"
                data-bs-toggle="tab" data-bs-target="#searchGrantTab"
                type="button" role="tab"
                aria-controls="searchGrantTab" aria-selected="false">
                Search New Grant</button>
          </li>
        </ul>
        <div id="tabs" class="tab-content p-4">
          <div
            id="addRoleTab"
            class="tab-pane fade show active"
            role="tabpanel"
            aria-labelledby="new-role-tab">
            <%= turbo_frame_tag "new_role", src: new_role_path %>
            <div id="roleCreatedMessage"></div>
          </div>
          <div
            id="searchRoleTab"
            class="tab-pane fade"
            role="tabpanel"
            aria-labelledby=search-role-tab">
            <div id="roleUpdatedMessage"></div>
            <%= render "shared/search", path: search_roles_path %>
            <div id="roleResult"></div>
          </div>
          <div
            id="newGrantTab"
            class="tab-pane fade"
            role="tabpanel"
            aria-labelledby="new-grant-tab">
            <%= turbo_frame_tag "new_grant", src: new_grant_path %>
            <div id="grantCreatedMessage"></div>
          </div>
          <div
            id="searchGrantTab"
            class="tab-pane fade"
            role="tabpanel"
            aria-labelledby="grant-search-tab">
            <div id="grantUpdatedMessage"></div>
            <%= render "shared/search", path: search_grants_path %>
            <div id="grantCreatedMessage"></div>
          </div>
      </div>
      <div class="modal-footer">
        <a
          class="btn btn-primary btn-sm" href="#information"
          data-bs-toggle="collapse" role="button"
          aria-expanded="false" aria-controls="information">Information about Grants</a>
        <div id="information" class="collapse">
          <p class="fs-6">
            Note that almost every controller depends on the "manage_user" grants.<br/>
            So be careful with when you play with this grant.<br/>
            Likewise the post controller depends on
            "read, write and delete_and_edit_others"
            grants. <br/>
            If you're not going to plan remove these controller,
            don't interact with them.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
   <ul>
     <% object.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "AuthP", root_path, class: "navbar-brand" %>

    <button
        class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbarNav" class="sticky-top collapse navbar-collapse justify-content-between">
      <ul class="navbar-nav d-flex align-items-center">
        <li class="nav-item d-flex">
          <%= link_to "About", about_greeter_index_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
         <li class="nav-item d-flex">
           <%= link_to "All posts", posts_path, class: "nav-link" %>
         </li>
        <% end %>
      </ul>
      <div class="d-flex justify-content-around">
        <% unless user_signed_in? %>
          <button
              class="btn btn-light d-flex"
              type="button"
              data-bs-toggle="modal" data-bs-target="#signInModal">
              Sign-in</button>
          <button
              class="btn btn-secondary d-flex"
              type="button"
              data-bs-toggle="modal" data-bs-target="#signUpModal">
              Sign-up</button>
        <% else %>
          <button
              class="btn btn-info d-flex"
              type="button"
              data-bs-toggle="modal" data-bs-target="#editUserModal">
              <%= current_user.email %></button>
          <% if current_user.granted_for? "manage_users" %>
              <button
                class="btn btn-warning d-flex"
                type="button"
                data-bs-toggle="modal" data-bs-target="#manageUser">
                Control Roles/Grants</button>
          <% end %>
          <%= link_to "Logout", active_session_path(current_user.active_sessions.last),
            method: :delete,
            "data-turbo-method": "delete",
            class: "btn btn-danger d-flex"
          %>
        <% end %>
       </div>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<%= form_with url: path do |form| %>
  <%= form.label :query, "Search", class: "form-label" %>
  <%= form.text_field :query, class: "form-control mb-2" %>
  <%= form.submit "Search", class: "btn btn-primary", data: { disable_with: false } %>
<% end %>

app/views/shared/_session_links.html.erb
<div class="btn-group d-flex fixed-buttom" role="group">
  <% button_classes = "btn btn-primary" %>
  <% sign_up_button = link_to "Sign up", new_user_path, class: button_classes %>
  <% login_button = link_to "Login", new_sessions_path, class: button_classes %>
  <% forget_password_button = link_to "Password Reseting", new_password_path, class: button_classes %>
  <% if purpose == :login %>
    <%= sign_up_button %>
    <%= forget_password_button %>
  <% elsif purpose == :register %>
    <%= login_button %>
    <%= forget_password_button %>
  <% elsif purpose == :password %>
    <%= login_button %>
    <%= sign_up_button %>
  <% end %>
</div>

app/views/shared/_user_actions.html.erb
<div id="<%= modal_id %>" class="modal fade" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= turbo_frame_tag action_id, src: action_path %>
      </div>
    </div>
  </div>
</div>