config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # You might think that using resource only for index is strange.
  # This looks familiar and it's clear that what i'm doing to
  resources :greeter, only: %i[index] do
    collection { get 'about' }
  end

  resource :sessions, only: %i[new create destroy]
  resources :users, except: %i[index] do
    member { post :update_role }
  end
  resources :posts
  resources :roles, except: %i[index show] do
    collection { post :search }
  end
  resources :grants, except: %i[index show] do
    collection { post :search }
  end
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  resources :passwords, except: %i[index destroy show], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection { delete 'destroy_all' }
  end

  root to: 'greeter#index'
end

app/models/role.rb
# frozen_string_literal: true

# Manages the status of the User
class Role < ApplicationRecord
  has_many :users
  has_many :role_model_associations, dependent: :destroy
  has_many :grants, through: :role_model_associations

  after_commit { Kredis.clear_all }
  before_destroy :save_the_users

  # This macro defines some methods which queries the grants of the role
  # They returns boolean
  # Note that this model does not queries the cache or reads cache
  # Example usage: admin.can_read?
  Grant.pluck(:name).each do |grant_name|
    define_method("can_#{grant_name}?") do
      grants.find_by(name: grant_name).present?
    end
  end

  private

  def save_the_users
    users.find_each do |user|
      user.role = Role.first
      user.save
    end
  end

  def cache_users_grant
    Kredis.clear_all

    User.cache_every_users_grant
  end
end

app/controllers/roles_controller.rb
# frozen_string_literal: true

# This controller provides CRUD actions for role
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permissions_for_manage_users
  before_action :set_role, only: %i[edit update destroy]

  # @return [void]
  def new
    @role = Role.new
  end

  # @return [void]
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_back fallback_location: root_path, notice: 'Role was successfully created' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('roleCreatedMessage', partial: 'ok_message')
        end
      else
        format.html { render :new, status: :unprocessable_entity }

        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('roleCreatedMessage', partial: 'err_message')
        end
      end
    end
  end

  # @return [void]
  def edit; end

  # @return [void]
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: :root_path, notice: 'This role is destroyed' }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('roleUpdatedMessage', 'del_message')
      end
    end
  end

  # @return [void]
  def update
    respond_to do |format|
      if @role.update(role_params)
        User.cache_every_users_grant
        format.html { redirect_to role_url(@role), notice: 'Role was updated' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('roleUpdatedMessage', partial: 'ok_message')
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('roleUpdatedMessage', partial: 'err_message')
        end
      end
    end
  end

  # @return [void]
  def search
    respond_to do |format|
      format.turbo_stream do
        @roles = Role.where('name LIKE ?', "%#{params[:query]}%")

        render turbo_stream: turbo_stream.append(
          'roleResult', partial: 'result'
        )
      end
    end
  end

  private

  # @return [Role]
  def set_role
    @role = Role.find(params[:id])
  end

  # @return [ActionController::Parameters]
  def role_params
    params.require(:role).permit(:name, grant_ids: [])
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_del_message.html.erb
<p>The requested role is deleted</p>

app/views/roles/_err_message.html.erb
<p>There is some issues with the role</p>

app/views/roles/_form.html.erb
<%= form_with model: role do |form| %>
  <%= form.label :name, class: "h4 form-label" %>
  <%= form.text_field :name, class: "form-control" %>
  <%= form.label :grants, class: "h4 form-label" %>
    <%= form.collection_check_boxes :grant_ids, Grant.all, :id, :name do |check| %>
      <div class="form-check">
        <%= check.check_box class: "form-check-input" %>
        <%= check.label class: "form-check-label" %>
      </div>
    <% end %>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/roles/_ok_message.html.erb
<p>Ok! Your role is ready</p>

app/views/roles/_result.html.erb
<div class="roles">
  <% @roles.find_each do |role| %>
    <%= turbo_frame_tag dom_id(role), src: edit_role_path(role) %>
  <% end %>
  <% if @roles.empty? %>
    <em>Role does not found</em>
  <% end %>
</div>

app/views/roles/edit.html.erb
<%= turbo_frame_tag dom_id(@role) do %>
  <%= render "form", role: @role %>
  <%= button_to "Delete This Role", role_path(@role), method: :delete, class: "btn btn-danger" %>
<% end %>

app/views/roles/new.html.erb
<%= turbo_frame_tag "new_role" do %>
  <%= render "form", role: @role %>
<% end %>