config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # You might think that using resource only for index is strange.
  # This looks familiar and it's clear that what i'm doing to
  resources :greeter, only: %i[index] do
    collection { get 'about' }
  end

  resource :sessions, only: %i[new create destroy]
  resources :users, except: %i[index] do
    member { post :update_role }
  end
  resources :posts
  resources :roles, except: %i[index show] do
    collection { post :search }
  end
  resources :grants, except: %i[index show] do
    collection { post :search }
  end
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  resources :passwords, except: %i[index destroy show], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection { delete 'destroy_all' }
  end

  root to: 'greeter#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "AuthP", root_path, class: "navbar-brand" %>

    <button 
        class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbarNav" class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_sessions_path, class: "nav-link" %>
        </li>
        <li class="nav-link">
          <%= link_to "Register", new_users_path, class: "nav-link" %> 
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <header>
      <%= render "shared/navbar" %>
    <%= render "shared/alerts" %>
    <% if user_signed_in? %>
      <%= render "shared/user_actions",
        modal_id: "editUserModal",
        action_id: "user-edit",
        action_path: edit_user_path(current_user)
      %>
      <% if current_user.granted_for?("manage_users") %>
        <%= render "shared/control_panel" %>
      <% end %>
      <% else %>
        <%= render "shared/user_actions",
          modal_id: "signUpModal",
          action_id: "user-register",
          action_path: new_user_path
        %>
        <%= render "shared/user_actions",
          modal_id: "signInModal",
          action_id: "user-login",
          action_path: new_sessions_path
        %>
      <% end %>
    </header>

    <main class="bg-light bg-gradient container-fluid">
      <%= yield %>
    </main>
  </body>
</html>